name: Feed Cron

on:
  schedule:
    - cron: "0 6 * * *" # At 06:00.
  workflow_dispatch:

jobs:
  get-feed:
    runs-on: ubuntu-latest
    env:
      NOTION_KEY: ${{ secrets.NOTION_KEY }}
      NOTION_READER_DATABASE_ID: ${{ secrets.NOTION_READER_DATABASE_ID }}
      NOTION_FEEDER_DATABASE_ID: ${{ secrets.NOTION_FEEDER_DATABASE_ID }}
      DENO_DIR: deno

    steps:
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.27.0"

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Update Notion Feed
        run: |
          cd ../notion-rss-reader/
          echo "$(deno run -A --unstable --import-map=import_map.json index.ts)"