name: Feed Cron

on:
  schedule:
    - cron: "0 */8 * * *" # At minute 0 past every 8th hour.
  workflow_dispatch:

jobs:
  get-feed:
    runs-on: ubuntu-latest
    env:
      NOTION_KEY: ${{ secrets.NOTION_KEY }}
      NOTION_READER_DATABASE_ID: ${{ secrets.NOTION_READER_DATABASE_ID }}
      NOTION_FEEDER_DATABASE_ID: ${{ secrets.NOTION_FEEDER_DATABASE_ID }}
    steps:
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.8.2"
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Update Notion Feed
        run: |
          cd ../notion-rss-reader/
          echo "$(deno task start)"